### ISSUE TITLE
Support fragments

### ISSUE THREAD

**Issue by corysimmons** [unruffledBeaver/react-animation-components#5]

**Comment by chrisjcodes** [comment]
@corysimmons Can you please add some information about what youre requesting? Please follow the issue template: https://github.com/unruffledBeaver/react-animation-components/blob/master/ISSUE_TEMPLATE.md

**Comment by corysimmons** [comment]
Like how you can pass `component={null}` in http://reactcommunity.org/react-transition-group/transition-group#TransitionGroup-prop-component

Your lib should support same?

**Comment by chrisjcodes** [comment]
The `component` prop is passed through to `TransitionGroup` and should work the same way the API for that component does. Not sure why passing `null` isnt working but the `wrapper` components are not altering or blocking that prop. You may want to file a bug with `react-transition-group`
